### PR TITLE
Add files meant to go into /etc/gridftp.d

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
This change depends on #10

**Comment by bbockelm** [comment]
@matyasselmeci @brianhlin - this now has merge conflicts

(Brian - FWIW, you can push new commits to Matyas' branch)

**Comment by brianhlin** [comment]
@bbockelm fixed. And huh, how is pushing directly to his branch possible?

**Comment by bbockelm** [comment]
By default, GitHub checks the box that says "Allow maintainers to edit this branch" - that's why you can do tweaks to docs tickets that folks tweak.

**Pull request merged**
